### ISSUE TITLE
What is the purpose of reversing the input_ids?

### ISSUE THREAD

**Issue by ifed-ucsd** [OswaldHe/HMT-pytorch#10]
What is the purpose of reversing the input_ids in https://github.com/OswaldHe/HMT-pytorch/blob/2783384f3db55773064106b8e3957f00c63c931f/hmt_src/main.py#L221?

**Comment by OswaldHe** [comment]
Hi,

This is directly adapted from the codebase of [recurrent memory transformer](https://github.com/booydar/recurrent-memory-transformer/blob/framework_accel/run_finetuning_lm_rmt.py#L244C9-L248C86). The idea is to insert padding tokens in front of the segment rather than directly append them, so that memory embeddings will not extract too much information from the useless padding tokens. Notice that the collate function will later [flip the tensor back](https://github.com/OswaldHe/HMT-pytorch/blob/2783384f3db55773064106b8e3957f00c63c931f/hmt_src/main.py#L224) so that the order remains the same.

Zifan
